### ISSUE TITLE
Conversion of E-GEOD-23436 is missing study and assay files

### ISSUE THREAD

**Issue by sjhosui** [ISA-tools/MAGEtoISAconverter#9]
Hi again,

When I submit E-GEOD-23436 for conversion, I get a single investigation file and no study or assay files. Can you please help resolve this?

Thank you!

Best,
Shannan

**Comment by psm3426** [comment]
Hi Shannan,

I think the reason that there's only an investigation file is because the information in the investigation file comes from the IDF file while the other information comes from the SDRF file.  When looking at E-GEOD-23436 on ArrayExpress, it has two SDRF files, and the current version of this converter can't handle the case where there is more than one SDRF file.

Issue number 7 that I filed actually deals with this, and it looks like it's been flagged as a priority task, so hopefully the next version of the converter will be able to handle this even though having 2+ SDRF files is not valid formatting according to the current MAGE-Tab specification.
